AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-cli-lambda-serverless-test

  Sample SAM Template for sam-cli-lambda-serverless-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        PROFILE: prod
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
      - x86_64
      MemorySize: 512
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  # 회원 생성
  CreateUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.CreateUserHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE_NAME: !Ref MyUserTable
      # DB 연결 권한 부여.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyUserTable
      Events:
        CreateUser: #이벤트 이름
          Type: Api
          Properties:
            Path: /user
            Method: post

  # 회원 조회 (ID 기반)
  GetUserByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.GetUserByIdHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref MyUserTable
      # DB 연결 권한 부여.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyUserTable
      Events:
        GetUserById:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: get

  # 회원 조회 (Name 기반, scan)
  GetUserByNameScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.GetUserByNameScanHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          TABLE_NAME: !Ref MyUserTable
      # DB 연결 권한 부여.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyUserTable
      Events:
        GetUserByName:
          Type: Api
          Properties:
            Path: /user
            Method: get

  # 회원 조회 (Name 기반, index - Query)
  GetUserByNameQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.GetUserByNameQueryHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          TABLE_NAME: !Ref MyUserTable
      # DB 연결 권한 부여.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyUserTable
      Events:
        GetUserByName:
          Type: Api
          Properties:
            Path: /user/query
            Method: get

  # DB
  MyUserTable:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Retain
    Properties:
      TableName: MyUserTable
      PrimaryKey:
        Name: userId
        Type: String

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World 
      function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
